struct program : AST {AST_node decl_list;program();program(AST_node _decl_list);virtual std::vector <std::string> contents () const override; };
struct declList : AST {std::vector <AST_node> decls;declList();declList(std::vector <AST_node> _decls);virtual std::vector <std::string> contents () const override; };
struct decl : AST {AST_node sub_decl;decl();decl(AST_node _sub_decl);virtual std::vector <std::string> contents () const override; };
struct varDecl : AST {AST_node type_spec;AST_node name;AST_node size;varDecl();varDecl(AST_node _type_spec, AST_node _name, AST_node _size);virtual std::vector <std::string> contents () const override; };
struct typeSpecifier : AST {AST_node kwd_node;typeSpecifier();typeSpecifier(AST_node _kwd_node);virtual std::vector <std::string> contents () const override; };
struct funDecl : AST {AST_node type_spec;AST_node name;AST_node decl_list;AST_node body;funDecl();funDecl(AST_node _type_spec, AST_node _name, AST_node _decl_list, AST_node _body);virtual std::vector <std::string> contents () const override; };
struct formalDeclList : AST {std::vector <AST_node> decls;formalDeclList();formalDeclList(std::vector <AST_node> _decls);virtual std::vector <std::string> contents () const override; };
struct formalDecl : AST {AST_node type_spec;AST_node name;bool is_array;formalDecl();formalDecl(AST_node _type_spec, AST_node _name, bool _is_array);virtual std::vector <std::string> contents () const override; };
struct funBody : AST {AST_node decl_list;AST_node stmt_list;funBody();funBody(AST_node _decl_list, AST_node _stmt_list);virtual std::vector <std::string> contents () const override; };
struct localDeclList : AST {std::vector <AST_node> decls;localDeclList();localDeclList(std::vector <AST_node> _decls);virtual std::vector <std::string> contents () const override; };
struct statementList : AST {std::vector <AST_node> stmts;statementList();statementList(std::vector <AST_node> _stmts);virtual std::vector <std::string> contents () const override; };
struct statement : AST {AST_node sub_stmt;statement();statement(AST_node _sub_stmt);virtual std::vector <std::string> contents () const override; };
struct compoundStmt : AST {AST_node stmt_list;compoundStmt();compoundStmt(AST_node _stmt_list);virtual std::vector <std::string> contents () const override; };
struct assignStmt : AST {AST_node lvalue;AST_node rvalue;assignStmt();assignStmt(AST_node _lvalue, AST_node _rvalue);virtual std::vector <std::string> contents () const override; };
struct condStmt : AST {AST_node cond_expr;AST_node then_stmt;AST_node else_stmt;condStmt();condStmt(AST_node _cond_expr, AST_node _then_stmt, AST_node _else_stmt);virtual std::vector <std::string> contents () const override; };
struct loopStmt : AST {AST_node cond_expr;AST_node then_stmt;loopStmt();loopStmt(AST_node _cond_expr, AST_node _then_stmt);virtual std::vector <std::string> contents () const override; };
struct returnStmt : AST {AST_node rtrn_expr;returnStmt();returnStmt(AST_node _rtrn_expr);virtual std::vector <std::string> contents () const override; };
struct var : AST {AST_node name;AST_node size;var();var(AST_node _name, AST_node _size);virtual std::vector <std::string> contents () const override; };
struct expression : AST {AST_node lhs;AST_node op;AST_node rhs;expression();expression(AST_node _lhs, AST_node _op, AST_node _rhs);virtual std::vector <std::string> contents () const override; };
struct relop : AST {AST_node sym;relop();relop(AST_node _sym);virtual std::vector <std::string> contents () const override; };
struct addExpr : AST {AST_node lhs;AST_node op;AST_node rhs;addExpr();addExpr(AST_node _lhs, AST_node _op, AST_node _rhs);virtual std::vector <std::string> contents () const override; };
struct addop : AST {AST_node sym;addop();addop(AST_node _sym);virtual std::vector <std::string> contents () const override; };
struct term : AST {AST_node lhs;AST_node op;AST_node rhs;term();term(AST_node _lhs, AST_node _op, AST_node _rhs);virtual std::vector <std::string> contents () const override; };
struct mulop : AST {AST_node sym;mulop();mulop(AST_node _sym);virtual std::vector <std::string> contents () const override; };
struct factor : AST {AST_node rvalue;factor();factor(AST_node _rvalue);virtual std::vector <std::string> contents () const override; };
struct funcCallExpr : AST {AST_node name;AST_node arg_list;funcCallExpr();funcCallExpr(AST_node _name, AST_node _arg_list);virtual std::vector <std::string> contents () const override; };
struct argList : AST {std::vector <AST_node> args;argList();argList(std::vector <AST_node> _args);virtual std::vector <std::string> contents () const override; };
